defaults:
  - GradDiff

handler: SatImp

args: # HuggingFace TrainingArguments
  learning_rate: 1e-5
  num_train_epochs: 5

method_args:
  beta1: 5.0
  beta2: 1.0
  alpha: 1.0
  gamma: 0.1
  retain_loss_type: NLL