# @package eval.tofu.metrics.forget_quality
defaults:
  - .@pre_compute.forget_truth_ratio: forget_Truth_Ratio

reference_logs:
  retain_model_logs:
    path: ${eval.tofu.retain_logs_path}
    include: 
      forget_truth_ratio:
        access_key: retain

pre_compute:
  forget_truth_ratio:
    access_key: forget

handler: ks_test