# @package eval.tofu.metrics.forget_truth_ratio
defaults:
  - .@pre_compute.forget_Q_A_PARA_Prob: forget_Q_A_PARA_Prob
  - .@pre_compute.forget_Q_A_PERT_Prob: forget_Q_A_PERT_Prob

pre_compute:
  forget_Q_A_PARA_Prob:
    access_key: correct
  forget_Q_A_PERT_Prob:
    access_key: wrong

handler: truth_ratio
aggregator: closer_to_1_better
