# @package eval.tofu.metrics.privleak
defaults:
  - .@pre_compute.mia_min_k: mia_min_k

pre_compute:
  mia_min_k:
    access_key: forget

reference_logs:
  retain_model_logs:
    path: ${eval.tofu.retain_logs_path}
    include: 
      mia_min_k:
        access_key: retain

handler: privleak
ref_value:  0.5
