# @package eval.tofu.metrics.ra_Q_A_Prob_normalised
defaults:
  - .@pre_compute.ra_Q_A_Prob: ra_Q_A_Prob
  - .@pre_compute.ra_Q_A_PERT_Prob: ra_Q_A_PERT_Prob

pre_compute:
  ra_Q_A_Prob:
    access_key: correct
  ra_Q_A_PERT_Prob:
    access_key: wrong

handler: probability_w_options