# @package eval.tofu.metrics.wf_Q_A_Prob_normalised
defaults:
  - .@pre_compute.wf_Q_A_Prob: wf_Q_A_Prob
  - .@pre_compute.wf_Q_A_PERT_Prob: wf_Q_A_PERT_Prob

pre_compute:
  wf_Q_A_Prob:
    access_key: correct
  wf_Q_A_PERT_Prob:
    access_key: wrong

handler: probability_w_options