# @package eval.tofu.metrics.wf_Truth_Ratio
defaults:
  - .@pre_compute.wf_Q_A_Prob: wf_Q_A_Prob
  - .@pre_compute.wf_Q_A_PERT_Prob: wf_Q_A_PERT_Prob

pre_compute:
  wf_Q_A_Prob:
    access_key: correct
  wf_Q_A_PERT_Prob:
    access_key: wrong

handler: truth_ratio
aggregator: true_better
