model_config:
  model_name: tofu_Llama-3.2-1B-Instruct_full
  model_kwargs:
    pretrained_model_name_or_path: open-unlearning/tofu_Llama-3.2-1B-Instruct_full
    trust_remote_code: True
    device_map: auto

dataset_config:
  dataset_name: tofu
  dataset_kwargs:
    path: 'locuslab/TOFU'
    name: 'forget10'
    split: train
    cache_dir: _cache_data/

prompt_config:
  prompt_name: INST_QAS_LLAMA3_TEMPLATE
  examples_path: null
  fewshot_delimiter: "\n\n"

repeats: 5

generation_kwargs:
  max_new_tokens: 200
  do_sample: True
  temperature: 1.0

until:
  - "Question:"
  - "Question: "
  - "Q: "
  - "Q:"


batch_size: 1
padding_size: left
truncation: False
seed: 0
device: cuda
output_file: data/${model_config.model_name}/${dataset_config.dataset_kwargs.name}/alt${repeats}_seed_${seed}.json
# limit: 5