model_args:
  pretrained_model_name_or_path: "HuggingFaceH4/zephyr-7b-beta"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "HuggingFaceH4/zephyr-7b-beta"
template_args:
  apply_chat_template: True
  system_prompt: You are a helpful assistant.
  system_prompt_with_special_tokens: "<|system|>\nYou are a helpful assistant.</s>\n"
  user_start_tag: "<|user|>\n"
  user_end_tag: "</s>"
  asst_start_tag: "<|assistant|>\n"
  asst_end_tag: "</s>"
  date_string: 10 Apr 2025