# @package eval.muse.metrics.mia_gradnorm
defaults:
  - ../../data/datasets@datasets: MUSE_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
datasets:
  MUSE_MIA_holdout:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
  MUSE_MIA_forget:
    access_key: forget
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}

handler: mia_gradnorm
batch_size: 1
p: 2