# @package eval.muse.metrics.mia_min_k
defaults:
  - ../../data/datasets@datasets: MUSE_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
datasets:
  MUSE_MIA_holdout:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
  MUSE_MIA_forget:
    access_key: forget
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}

batch_size: 8
handler: mia_min_k
k: 0.4