name: tests

on:
  push:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/*.yml"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
        os:
          - "ubuntu-latest"

    runs-on: ubuntu-latest

    environment:
      name: tests

    env:
      # HF_TOKEN: ${{ secrets.HF_TOKEN }}
      OS_NAME: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.py"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.6

      - name: Check Quality
        run: make quality

      # - name: Test with pytest
      #   run: |
      #     cd <DIR>
      #     make test
